### ISSUE TITLE
tmux status bar

### ISSUE THREAD

**Issue by StoicPerlman** [arl/gitstatus#4]
I am trying to use this in place of your tmux-gitbar because I use zsh. I tried setting the status-right property `set -g status-right '#(gitstatus -q -fmt tmux #{pane_current_path})'`, as you suggested [here](https://github.com/arl/tmux-gitbar/issues/60), but it is always blank. 

I know gitstatus is working because if I run the command `gitstatus -q -fmt tmux $(pwd)` I get the expected output. I can actually take the output and set status-right and it shows everything correctly `set -g status-right '#[fg=default]#[fg=default]#[fg=white,bold]⎇ #[fg=default]master#[fg=default]..#[fg=cyan]origin/master#[fg=default]#[fg=default] - #[fg=magenta,bold]…1'`

I have tried zsh and bash. Any ideas on troubleshooting this? I am new to tmux so it might be my own ignorance. I actually want to switch to tmux full time just for this feature because I dislike my git status in my PS1.

I am using tmux 2.8 and zsh 5.6.2

**Comment by arl** [comment]
Which version of tmux at you using ?

**Comment by arl** [comment]
The only reason I can't think of is that maybe you didn't reload tmux configuration after adding the line to your `tmux.conf`.
Just adding a configuration setting is not enough, you need to either force a configuration reload, or a sure way is to exits from all open tmux sessions and start a new one.

This project really needs better documentation, I apologize for that. The thing is, after migrating my own config from tmuxgitbar to gitstatus, everything just works so I never had to get back to the project.

**Comment by StoicPerlman** [comment]
Leaving this here for anyone else who has the issue. This only happens when launching tmux automatically using the [tmux oh-my-zsh plugin](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/tmux). If you start tmux normally it works great. Not sure what that plugin does differently yet.

**Comment by StoicPerlman** [comment]
Fixed. Make sure to add your `$GOPATH/bin` to your path before you load oh-my-zsh.
