### ISSUE TITLE
Custom colors

### ISSUE THREAD

**Issue by nocode99** [arl/gitstatus#6]
Hi, thanks for writing this plugin!  I was wondering if you had any plans on adding the ability to customize the coloring?

**Comment by arl** [comment]
In fact, you already can customize colors and symbols :)

If you run `gitstatus -printcfg` you'll get the current config (the default one), save this to a new file.

```sh
$ gitstatus -printcfg > gitstatus.yml
$ cat gitstatus.yml
tmux:
  symbols:
    branch: '⎇ '
    hashprefix: ':'
    ahead: ↑·
    behind: ↓·
    staged: ●
    conflict: '✖ '
    modified: '✚ '
    untracked: …
    stashed: '⚑ '
    clean: ✔
  styles:
    state: '#[fg=red,bold]'
    branch: '#[fg=white,bold]'
    remote: '#[fg=cyan]'
    staged: '#[fg=green,bold]'
    conflict: '#[fg=red,bold]'
    modified: '#[fg=red,bold]'
    untracked: '#[fg=magenta,bold]'
    stashed: '#[fg=cyan,bold]'
    clean: '#[fg=green,bold]'
```
Edit the `styles` section with tmux style strings, for more info on the format, look up `message-command-style` in `man tmux`.

I admit that this tool needs a README :D

**Comment by nocode99** [comment]
Ah I see now and then add the `-cfg /path/to/gitstatus.yml` to the status config in tmux. Thanks!

**Comment by arl** [comment]
Yup exactly that's it.
By the way you should switch to github.com/arl/gitmux as gitstatus is in fact a library.

Gitmux has binary releases for all supported platforms and an actual documentation ;-)
